Repository MPSU/APS, pull requests merged in 2024-04, with the labels that each got.

#77 ЛР5. Дополнение кодирования SYSTEM инструкций
  .pic/Labs/lab_05_decoder/rv32i_summary.png
  .pic/Labs/lab_05_decoder/rv32i_summary.xlsx
  Labs/05. Main decoder/README.md
Labels: ЛР05

#78 brosandr.lab_13_uart_tx_sb_obf
  Labs/Made-up modules/lab_13.uart_tx_sb_ctrl.sv
Labels: ЛР13

#79 ЛР5. Связь описания сигналов с покодами
  Labs/05. Main decoder/README.md
Labels: ЛР05

#73 ЛР1. Замена generate на массив модулей
  .pic/Labs/lab_01_adder/fig_07.png
  Labs/01. Adder/README.md
  Labs/02. Arithmetic-logic unit/README.md
  Labs/12. Daisy chain/README.md
  Labs/15. Programming device/README.md
Labels: ЛР01, ЛР02, ЛР12, ЛР15

#81 Fix(labs/04/board/md):Испр-ие ссылки на program
  Labs/04. Primitive programmable device/board files/README.md
Labels: ЛР04
