Repository MPSU/APS, pull requests merged in 2024-07, with the labels that each got.

#89 Переработка лабораторных работ, связанных с памятью
  .github/SUMMARY.md
  .github/index.md
  .pic/Labs/lab_06_dp/fig_02.drawio.svg
  .pic/Labs/lab_06_main_memory/fig_01.png
  .pic/Labs/lab_06_main_memory/fig_01.xlsx
  .pic/Labs/lab_06_main_memory/fig_02.wavedrom.svg
  .pic/Labs/lab_06_main_memory/fig_03.wavedrom.svg
  .pic/Labs/lab_07_datapath.drawio.svg
  .pic/Labs/lab_07_dp/fig_01.drawio.svg
  .pic/Labs/lab_07_dp/fig_02.drawio.svg
  .pic/Labs/lab_07_dp/fig_02.excel.png
  .pic/Labs/lab_07_dp/fig_02.xlsx
  Labs/03. Register file and memory/README.md
  Labs/03. Register file and memory/memory_pkg.sv
  Labs/03. Register file and memory/tb_data_mem.sv
  Labs/03. Register file and memory/tb_instr_mem.sv
  Labs/05. Main decoder/README.md
  Labs/05. Main decoder/decoder_pkg.sv
  Labs/05. Main decoder/tb_decoder_riscv.sv
  Labs/06. Main memory/README.md
  Labs/06. Main memory/memory_pkg.sv
  Labs/07. Datapath/README.md
  Labs/07. Datapath/alu_opcodes_pkg.sv
  Labs/07. Datapath/board files/README.md
  Labs/07. Datapath/board files/nexys_a7_100t.xdc
  Labs/07. Datapath/board files/nexys_riscv_unit.sv
  Labs/07. Datapath/csr_pkg.sv
  Labs/07. Datapath/decoder_pkg.sv
  Labs/07. Datapath/memory_pkg.sv
  Labs/07. Datapath/program.mem
  Labs/07. Datapath/tb_riscv_unit.sv
  Labs/07. External memory/README.md
  Labs/08. Load-store unit/tb_lsu.sv
  Labs/Made-up modules/lab_06.data_mem.sv
  Labs/Made-up modules/lab_08.lsu.sv
  Labs/README.md
Labels: ЛР03, ЛР07

#91 ЛР13. Обновление готовых модулей uart
  Labs/Made-up modules/lab_13.uart_rx_sb_ctrl.sv
  Labs/Made-up modules/lab_13.uart_tx_sb_ctrl.sv
Labels: ЛР13

#96 ЛР13. Обновление vga шрифтов
  Labs/13. Peripheral units/README.md
  Labs/13. Peripheral units/firmware/mem_files/lab_13_vga_ch_t.mem
Labels: ЛР13

#97 ЛР16. Рефактор методички
  Labs/16. Coremark/Makefile
  Labs/16. Coremark/README.md
  Labs/16. Coremark/linker_script.ld
  Labs/16. Coremark/startup.S
Labels: ЛР16
